local LeaderboardDefinitions = {}

-- TopCount values are clamped so user-edited definitions cannot request unsafe page sizes.
local MIN_TOP_COUNT = 1
local MAX_TOP_COUNT = 100

-- ORDER controls README examples, Command Bar board creation order, and display registration order.
local ORDER = {
	"Score",
	"Wins",
	"Level",
}

-- DEFINITIONS_BY_ID is the only required edit point for adding or removing leaderboards.
-- Id: stable API/attribute value used by SetPlayerValue and Workspace parts.
-- DisplayName: user-facing title used when the part does not override LeaderboardTitle.
-- MetaKey: optional adapter key for UpdatePlayerFromState helpers.
-- DataStoreName: OrderedDataStore name; change the prefix for your own game before shipping.
-- SortAscending: false means highest value wins, true means lowest value wins.
-- TopCount: default number of rows requested and generated by the Command Bar script.
-- RemoveZeroValues: true removes zero values from the OrderedDataStore.

local DEFINITIONS_BY_ID = {
	Score = {
		Id = "Score",
		DisplayName = "Top Score",
		MetaKey = "Score",
		DataStoreName = "GenericLeaderboard_Score",
		SortAscending = false,
		TopCount = 10,
		RemoveZeroValues = true,
	},

	Wins = {
		Id = "Wins",
		DisplayName = "Most Wins",
		MetaKey = "Wins",
		DataStoreName = "GenericLeaderboard_Wins",
		SortAscending = false,
		TopCount = 10,
		RemoveZeroValues = true,
	},

	Level = {
		Id = "Level",
		DisplayName = "Highest Level",
		MetaKey = "Level",
		DataStoreName = "GenericLeaderboard_Level",
		SortAscending = false,
		TopCount = 10,
		RemoveZeroValues = true,
	},
}

-- Returns a shallow copy so consumers cannot mutate the source-of-truth table.
local function copyDefinition(definition)
	if type(definition) ~= "table" then
		return nil
	end

	return table.clone(definition)
end

-- Converts user input into a non-empty leaderboard id or nil.
local function sanitizeLeaderboardId(leaderboardId)
	local safeLeaderboardId = tostring(leaderboardId or "")
	if safeLeaderboardId == "" then
		return nil
	end

	return safeLeaderboardId
end

-- Converts user input into a whole number that is never below zero.
local function sanitizeWholeNumber(value)
	return math.max(0, math.floor(tonumber(value) or 0))
end

-- Clamps a requested leaderboard row count to the supported range.
function LeaderboardDefinitions.NormalizeTopCount(value, fallback, maxCount)
	local safeMaxCount = sanitizeWholeNumber(maxCount)
	if safeMaxCount <= 0 or safeMaxCount > MAX_TOP_COUNT then
		safeMaxCount = MAX_TOP_COUNT
	end

	local safeValue = sanitizeWholeNumber(value)
	if safeValue <= 0 then
		safeValue = sanitizeWholeNumber(fallback)
	end
	if safeValue <= 0 then
		safeValue = MIN_TOP_COUNT
	end

	return math.min(math.max(safeValue, MIN_TOP_COUNT), safeMaxCount)
end

-- Returns one definition by id, or nil when the id is unknown.
function LeaderboardDefinitions.GetDefinition(leaderboardId)
	local safeLeaderboardId = sanitizeLeaderboardId(leaderboardId)
	if safeLeaderboardId == nil then
		return nil
	end

	return copyDefinition(DEFINITIONS_BY_ID[safeLeaderboardId])
end

-- Checks whether an id exists in the source-of-truth definitions.
function LeaderboardDefinitions.IsRegistered(leaderboardId)
	local safeLeaderboardId = sanitizeLeaderboardId(leaderboardId)
	return safeLeaderboardId ~= nil and DEFINITIONS_BY_ID[safeLeaderboardId] ~= nil
end

-- Returns definitions in the configured order.
function LeaderboardDefinitions.GetOrderedDefinitions()
	local result = {}

	for _, leaderboardId in ipairs(ORDER) do
		local definition = DEFINITIONS_BY_ID[leaderboardId]
		if definition ~= nil then
			result[#result + 1] = copyDefinition(definition)
		end
	end

	return result
end

-- Returns all definitions keyed by id.
function LeaderboardDefinitions.GetAllDefinitions()
	local result = {}

	for leaderboardId, definition in pairs(DEFINITIONS_BY_ID) do
		result[leaderboardId] = copyDefinition(definition)
	end

	return result
end

-- Returns registered ids in display/creation order.
function LeaderboardDefinitions.GetRegisteredIds()
	local result = {}

	for _, leaderboardId in ipairs(ORDER) do
		if DEFINITIONS_BY_ID[leaderboardId] ~= nil then
			result[#result + 1] = leaderboardId
		end
	end

	return result
end

-- Validates one definition and returns false plus a stable reason string when invalid.
function LeaderboardDefinitions.ValidateDefinition(definition)
	if type(definition) ~= "table" then
		return false, "InvalidDefinition"
	end

	if type(definition.Id) ~= "string" or definition.Id == "" then
		return false, "MissingId"
	end

	if type(definition.DisplayName) ~= "string" or definition.DisplayName == "" then
		return false, "MissingDisplayName"
	end

	if type(definition.MetaKey) ~= "string" or definition.MetaKey == "" then
		return false, "MissingMetaKey"
	end

	if type(definition.DataStoreName) ~= "string" or definition.DataStoreName == "" then
		return false, "MissingDataStoreName"
	end

	if type(definition.TopCount) ~= "number" or definition.TopCount < MIN_TOP_COUNT or definition.TopCount > MAX_TOP_COUNT then
		return false, "InvalidTopCount"
	end

	return true, nil
end

-- Validates the full registry, including ORDER/definition consistency.
function LeaderboardDefinitions.ValidateAll()
	local seenById = {}

	for _, leaderboardId in ipairs(ORDER) do
		local safeLeaderboardId = sanitizeLeaderboardId(leaderboardId)
		if safeLeaderboardId == nil then
			return false, "OrderContainsInvalidId"
		end

		if seenById[safeLeaderboardId] then
			return false, safeLeaderboardId .. ":DuplicateOrderId"
		end
		seenById[safeLeaderboardId] = true

		local definition = DEFINITIONS_BY_ID[safeLeaderboardId]
		if type(definition) ~= "table" then
			return false, safeLeaderboardId .. ":MissingDefinition"
		end

		if definition.Id ~= safeLeaderboardId then
			return false, safeLeaderboardId .. ":DefinitionIdMismatch"
		end

		local success, reason = LeaderboardDefinitions.ValidateDefinition(definition)
		if not success then
			return false, safeLeaderboardId .. ":" .. tostring(reason)
		end
	end

	for leaderboardId, definition in pairs(DEFINITIONS_BY_ID) do
		local safeLeaderboardId = sanitizeLeaderboardId(leaderboardId)
		if safeLeaderboardId == nil then
			return false, "DefinitionsContainInvalidId"
		end

		if not seenById[safeLeaderboardId] then
			return false, safeLeaderboardId .. ":MissingFromOrder"
		end

		if type(definition) ~= "table" or definition.Id ~= safeLeaderboardId then
			return false, safeLeaderboardId .. ":DefinitionIdMismatch"
		end
	end

	return true, nil
end

return LeaderboardDefinitions
